name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject Webhook URL
        run: |
          # Zamieniamy placeholder na sekret o nazwie DISCORD_URL
          sed -i 's|MY_SECRET_WEBHOOK_URL|${{ secrets.DISCORD_URL }}|g' script.js
        # WAŻNE: Upewnij się, że Twój plik z kodem to 'script.js'. 
        # Jeśli ma inną nazwę, zmień ją powyżej.

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages
